# File based on:
# https://github.com/pybind/cmake_example/blob/master/conda.recipe/meta.yaml
# https://scikit-build-core.readthedocs.io/en/stable/faqs.html#making-a-conda-recipe
# https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files

{% set version_match = load_file_regex(load_file="VERSION", regex_pattern='(\\d+\\.\\d+\\.\\d+)') %}
{% set version = version_match[1] %}

package:
  name: xmipp4-compute-cuda
  version: "0.1.0"

about:
  summary: MPI Collective Communications library for xmipp4
  license_file: LICENSE

source:
  path: ../

requirements:
  run:
    - xmipp4-core=0.1

  host:
    - python
    - pip
    - scikit-build-core
    - xmipp4-core=0.1

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.16
    - ninja

build:
  number: 0
